# Generated by Django 3.2.16 on 2023-11-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SPP',
            fields=[
                ('id_spp', models.IntegerField(primary_key=True, serialize=False)),
                ('tahun', models.IntegerField()),
                ('nominal', models.IntegerField()),
            ],
        ),
    ]
