# Generated by Django 3.2.16 on 2023-11-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kelas',
            name='id_kelas',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
