# Generated by Django 3.2.16 on 2023-11-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelas', '0002_alter_kelas_id_kelas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kelas',
            name='id_kelas',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
