# Generated by Django 3.2.16 on 2023-11-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Petugas',
            fields=[
                ('id_petugas', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=32)),
                ('nama_petugas', models.CharField(max_length=35)),
                ('level', models.CharField(choices=[('admin', 'Admin'), ('petugas', 'Petugas')], max_length=7)),
            ],
        ),
    ]
