# Generated by Django 3.2.16 on 2023-11-21 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('petugas', '0001_initial'),
        ('spp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id_pembayaran', models.IntegerField(primary_key=True, serialize=False)),
                ('nisn', models.CharField(max_length=10)),
                ('tgl_bayar', models.DateField()),
                ('bulan_dibayar', models.CharField(max_length=8)),
                ('tahun_dibayar', models.CharField(max_length=4)),
                ('jumlah_bayar', models.IntegerField()),
                ('id_petugas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petugas.petugas')),
                ('id_spp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spp.spp')),
            ],
        ),
    ]
