# Generated by Django 5.0.1 on 2024-01-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pembayaran', '0002_alter_pembayaran_nisn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembayaran',
            name='bulan_dibayar',
            field=models.CharField(choices=[('1', 'Januari'), ('2', 'Februari'), ('3', 'Maret'), ('4', 'April'), ('5', 'Mei'), ('6', 'Juni'), ('7', 'Juli'), ('8', 'Agustus'), ('9', 'September'), ('10', 'Oktober'), ('11', 'November'), ('12', 'Desember')], max_length=2),
        ),
        migrations.AlterField(
            model_name='pembayaran',
            name='id_pembayaran',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
