# Generated by Django 5.0.1 on 2024-01-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pembayaran', '0003_alter_pembayaran_bulan_dibayar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembayaran',
            name='id_pembayaran',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
