# Generated by Django 5.0.2 on 2024-02-26 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pembayaran', '0006_remove_pembayaran_sudah_dicetak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembayaran',
            name='tgl_bayar',
            field=models.IntegerField(),
        ),
    ]
