# Generated by Django 3.2.16 on 2023-11-21 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kelas', '0001_initial'),
        ('spp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('nisn', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nis', models.CharField(max_length=8)),
                ('nama', models.CharField(max_length=35)),
                ('alamat', models.TextField()),
                ('no_telp', models.CharField(max_length=13)),
                ('id_kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kelas.kelas')),
                ('id_spp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spp.spp')),
            ],
        ),
    ]
