# Generated by Django 5.0.1 on 2024-01-15 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pembayaran', '0006_remove_pembayaran_sudah_dicetak'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryPembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_bayar', models.DateField(auto_now_add=True)),
                ('pembayaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pembayaran.pembayaran')),
            ],
        ),
    ]
