# Generated by Django 5.0.1 on 2024-01-15 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history_pembayaran', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historypembayaran',
            old_name='tanggal_bayar',
            new_name='tgl_bayar',
        ),
    ]
