# Generated by Django 5.0.1 on 2024-01-15 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history_pembayaran', '0002_rename_tanggal_bayar_historypembayaran_tgl_bayar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historypembayaran',
            old_name='tgl_bayar',
            new_name='tanggal_bayar',
        ),
    ]
